name: terraform
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual mode"
        required: true
        default: "test run..."


jobs:
  
  plan:
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    runs-on: ['ubuntu-latest']

    steps:
    - uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 0.14.2

    - run: terraform init

    - id: plan
      run: terraform plan -no-color

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}

